version: '3.8'

services:
  nginx:
    container_name: symfony_nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    container_name: symfony_php
    build:
      context: ./.docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: symfony_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

volumes:
  mysql_data: 